### ISSUE TITLE
Header-only libraries still need to be installed

### ISSUE THREAD

**Issue by adamnovak** [vgteam/dsgvg#3]
https://github.com/vgteam/dg/blob/43e5527253f6a16f1fb0e7bb21124eabec24cd57/CMakeLists.txt#L62

You need to do something like this https://stackoverflow.com/a/21223763 and have an INSTALL_COMMAND to actually put the headers in place I think.

**Comment by adamnovak** [comment]
Wait no the variables are supposed to just point to the include directories in wherever cmake puts the external project. So why is Emily not getting any headers for sparsepp?

**Comment by ekg** [comment]
I think this is resolved. Open again if not.
